name: Mirror to Backup

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to backup repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add backup https://<BACKUP_TOKEN>@github.com/<Renjithcr20>/<primary-repo-backup>.git
          git push --mirror backup
